server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #绑定rabbitmq的服务信息
        defaultRabbit: #定义名称，用于bnding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关配置环境
            spring:
              rabbitmq:
                host: 192.168.1.5
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        output: #通道名称
          destination: studyExchange #表示要使用的exchange名称定义
          conent-type: application/json #设置消息类型，本次为json，文本为text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔，默认30s
    lease-expiration-duration-in-seconds: 5 #如果现在超过5s时间，默认90s
    instance-id: send-8801.com #在消息列表中主机名称
    prefer-ip-address: true #访问的路径变为Ip地址