server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848
    sentinel:
      transport:
        # dashboard地址，8080监控8401
        dashboard: localhost:8080
        # 默认端口，若被占用就+1继续尝试
        port: 8719
        datasource: #数据持久化到nacos
          ds1:
            nacos:
              server-addr: 192.168.1.5:8848
              dataId: cloudalibaba-sentinel-service
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow
manegement:
  endpoints:
    web:
      exposure:
        include: "*"
