server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启自动路由功能
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，最好配合服务名称
          #uri: http://localhost:8001 #匹配后提供服务的路由地址,匹配指定路由
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #通过微服务名实现动态路由，配合自动路由enable使用
          predicates:
            - Path=/payment/hystrix/ok/** #断言，路径匹配后进行路由
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/hystrix/timeout/**

eureka:
  client:
    #向注册中心注册自己
    register-with-eureka: true
    #是否从Eureka server抓取已有的注册信息，默认为true，单节点无所谓，但是集群必须设置true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: cloud-gateway-service