server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_group
      nacos:
        discovery:
          server-addr: 192.168.1.5:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/seata_order
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
feign:
  hystrix:
    enabled: false
lodding:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml