server:
  port: 7001

eureka:
  instance:
    #同一台机器虚拟两个注册中心，需要在hosts文件中进行映射 127.0.0.1 eureka700x.com
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false

    #设置与eureka server交互的地址 查询和注册服务都需要这个地址
    service-url:
      #互相注册 注册别的地址！
      #defaultZone: http://eureka7002.com:7002/eureka/

      #单机设置的地址为自己，但是多机需要相互注册，设置其他机器的地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
